version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Mahiroot@33311333 # <<<<<<< IMPORTANT: CHANGE THIS TO A STRONG, UNIQUE PASSWORD
      MYSQL_DATABASE: marriage_bureau_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: Mahispring@33311333 # <<<<<<< IMPORTANT: CHANGE THIS TO A STRONG, UNIQUE PASSWORD
    ports:
      - "3306:3306" # This maps the container's 3306 to the Codespace's 3306
    volumes:
      - mysql_data:/var/lib/mysql # This persists your database data
      # Optional: Uncomment and configure this if you have an initial SQL script (e.g., schema.sql, data.sql)
      # - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s # Give MySQL a bit more time to start initially
volumes:
  mysql_data: # Define the named volume for data persistence