-- src/main/resources/db/migration/V1__Create_tables.sql

-- 1. Create the app_users table (parent table) FIRST
-- This table is critical as it's the core user entity.
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- H2 auto-incrementing primary key
    email VARCHAR(255) NOT NULL UNIQUE,                    -- Email serves as username for login
    password VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20),
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_app_users_email ON app_users (email);

-- 2. profiles table (child table linked to app_users)
CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT NOT NULL UNIQUE, -- Foreign key to app_users, one profile per user

    -- Core Profile Details
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(10),
    religion VARCHAR(50),
    caste VARCHAR(50),
    sub_caste VARCHAR(50),
    marital_status VARCHAR(20),
    height_cm DECIMAL(5, 2),
    complexion VARCHAR(50),
    body_type VARCHAR(20),
    education VARCHAR(100),
    occupation VARCHAR(100),
    annual_income DECIMAL(15, 2), -- Renamed from income_level
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    about_me TEXT,                 -- Renamed from bio
    photo_url VARCHAR(255),        -- Renamed from profile_picture_url
    is_active BOOLEAN DEFAULT TRUE NOT NULL,

    -- Preferred Partner Attributes
    preferred_partner_min_age INTEGER,
    preferred_partner_max_age INTEGER,
    preferred_partner_religion VARCHAR(50),
    preferred_partner_caste VARCHAR(50),
    preferred_partner_min_height_cm DECIMAL(5, 2),
    preferred_partner_max_height_cm DECIMAL(5, 2),

    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (app_user_id) REFERENCES app_users(id) ON DELETE CASCADE
);
CREATE INDEX idx_profiles_app_user_id ON profiles (app_user_id);


-- Other tables (like matches, messages) would follow here.
-- The 'user_roles' and 'preferences' tables have been removed
-- as they were determined to be redundant with your current entity design.