-- src/main/resources/db/migration/V1__Create_tables.sql

-- 1. Create the app_users table (parent table) FIRST
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE, -- Added: This was missing in your V1 but referenced in V2
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20), -- Added: This was missing in your V1 but referenced in V2
    role VARCHAR(255), -- Or use a separate roles table and foreign key if roles are complex
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Added: This was missing in your V1 but referenced in V2
    last_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Added: This was missing in your V1 but referenced in V2
);

-- 2. Create the user_roles table if you are using it (assuming it's a many-to-many or separate role table)
-- If this table doesn't exist, the V2 insert into user_roles will fail.
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_name VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role_name),
    FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

-- 3. Create the profiles table (child table) SECOND
CREATE TABLE profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    app_user_id BIGINT NOT NULL UNIQUE, -- Ensure this matches the FK name 'app_user_id'
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(10),
    religion VARCHAR(50),
    marital_status VARCHAR(20),
    occupation VARCHAR(100), -- Corrected: 'Occupation' to 'occupation' for consistency, though H2 is often case-insensitive
    income_level VARCHAR(50),
    education VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    phone_number VARCHAR(20),
    bio TEXT,
    profile_picture_url VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (app_user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

-- 4. Create the preferences table (since V2 tries to insert into it)
CREATE TABLE preferences (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE, -- This column name 'user_id' matches your V2 insert for preferences
    preferred_age_min INTEGER,
    preferred_age_max INTEGER,
    preferred_gender VARCHAR(10),
    preferred_religion VARCHAR(50),
    preferred_marital_status VARCHAR(20),
    preferred_city VARCHAR(100),
    preferred_state VARCHAR(100),
    preferred_country VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

-- 5. Continue with any other table creations (matches, messages, payments, notifications)
-- Ensure any tables with foreign keys also follow the parent-first rule.