// src/main/java/com/marriagebureau/usermanagement/dto/AuthResponse.java
package com.marriagebureau.usermanagement.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AuthResponse {
    // Renamed 'token' to 'accessToken' to match frontend expectation
    private String accessToken;
    private String tokenType = "Bearer"; // Renamed 'type' to 'tokenType' for consistency
    private Long id;
    private String email;
    private String username; // Added username as discussed in AuthService
    private String role; // Or a list of roles if applicable

    // Constructor explicitly for token and core user details
    public AuthResponse(String accessToken, Long id, String email, String username, String role) {
        this.accessToken = accessToken;
        this.id = id;
        this.email = email;
        this.username = username; // Assign username
        this.role = role;
    }

    // You can keep the AllArgsConstructor generated by Lombok for other scenarios,
    // or manually define constructors for specific needs if not using Lombok's AllArgsConstructor.
}